#!/bin/sh
#
# @name Pixel SC
#
# @type Glider
# @class Plane
#
# @output MAIN2 left wing
# @output MAIN3 right wing
# @output MAIN4 throttle (motor)
#
# @maintainer Roman Dvorak <dvorakroman@thunderfly.cz>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.fw_defaults

param set-default FW_AIRSPD_MIN10
param set-default FW_AIRSPD_TRIM 15
param set-default FW_AIRSPD_MAX 20

param set-default FW_MAN_P_MAX 30
param set-default FW_MAN_R_MAX 30
param set-default FW_R_LIM 30

param set-default FW_WR_FF 0.2
param set-default FW_WR_I 0.2
param set-default FW_WR_IMAX 0.8
param set-default FW_WR_P 1
param set-default FW_W_RMAX 0

# set disarmed value for the ESC
param set-default PWM_MAIN_DISARM 1000

set MIXER plane_pixelSC

# use PWM parameters for throttle channel
set PWM_OUT 4